//
//  _ConditionalNode.swift
//  GHFollowers
//
//  Created by Benjamín Guzmán López on 06-02-26.
//

import UIKit

/// Internal node generated by `@NodeBuilder` for `if/else` branches.
public struct _ConditionalNode<TrueContent: RepresentableNode, FalseContent: RepresentableNode>:
    RepresentableNode
{
    /// Stores which branch of the conditional is active.
    public enum Storage {
        /// The `if` branch node.
        case trueContent(TrueContent)

        /// The `else` branch node.
        case falseContent(FalseContent)
    }

    /// Active conditional storage branch.
    public let storage: Storage

    /// Creates a conditional node with preselected storage.
    public init(storage: Storage) {
        self.storage = storage
    }

    /// Builds the active branch into a concrete view.
    public func build(in context: BuildContext) -> UIView {
        switch storage {
        case .trueContent(let trueContent):
            trueContent.build(in: context)
        case .falseContent(let falseContent):
            falseContent.build(in: context)
        }
    }
}
