//
//  _TupleNode.swift
//  GHFollowers
//
//  Created by Benjamín Guzmán López on 06-02-26.
//

import UIKit

/// Internal node generated by `@NodeBuilder` for multiple child expressions.
public struct _TupleNode<each Child: RepresentableNode>: RepresentableNode {    
    /// Variadic tuple of child nodes.
    public let children: (repeat each Child)

    /// Creates a tuple node from variadic child values.
    public init(_ value: repeat each Child) {
        self.children = (repeat each value)
    }

    /// Builds child nodes wrapped into a single container view.
    public func build(in context: BuildContext) {
        for child in repeat each children {
            child.build(in: context)
        }
    }
}
