//
//  _TupleNode.swift
//  GHFollowers
//
//  Created by Benjamín Guzmán López on 06-02-26.
//

import UIKit

/// Internal node generated by `@NodeBuilder` for multiple child expressions.
public struct _TupleNode<each Child: RepresentableNode>: RepresentableNode {
    /// Variadic tuple of child nodes.
    public let children: (repeat each Child)

    /// Creates a tuple node from variadic child values.
    public init(_ value: repeat each Child) {
        self.children = (repeat each value)
    }

    /// Builds child nodes wrapped into a single container view.
    public func build() -> some UIView {
        // if someone asks for a single view, wrap
        let container = UIView()
        for child in buildList() { container.addSubview(child) }
        return container
    }

    /// Builds and flattens all child views in declaration order.
    public func buildList() -> [UIView] {
        var views: [UIView] = []

        for child in repeat each children {
            views.append(contentsOf: child.buildList())
        }

        return views
    }
}
